image: python:3.6

pipelines:
    tags:
        '*':
            - step:
                script:
                    - pip install -U tox wheel twine
                    - tox -e py36
                    - ./deploy.bash
